services:
  # Backend API service
  - type: web
    name: highlight-ai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --timeout 120 --keep-alive 65 --log-level info --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: NOTION_REDIRECT_URI
        sync: false
    runtime: python
    healthCheckPath: /api/health