services:
  # Backend API service
  - type: web
    name: highlight-ai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: NOTION_REDIRECT_URI
        sync: false
    healthCheckPath: /api/health